[build]
  command = "npm run build"
  publish = "build"
  environment = { NODE_OPTIONS = "--max-old-space-size=4096" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/weather/*"
  to = "https://api.openweathermap.org/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/desease/*"
  to = "http://ncpms.rda.go.kr/npmsAPI/service/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/bestfarm/*"
  to = "https://apis.data.go.kr/1390000/SmartFarmdata/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/smart/*"
  to = "https://www.smartfarmkorea.net/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/desaster/*"
  to = "https://www.safetydata.go.kr/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/payment/*"
  to = "https://api.portone.io/v1/payments/cancel/:splat"  
  status = 200
  force = true